Add Shell.ID() and Shell.ID(peer)
So I can find the local peer's ID for IPNS references.  The
/ipns/local resolution is specific to the FUSE implementation, so it
doesn't work directly with the non-FUSE commands:

  $ ipfs ls /ipns/local
  Error: could not resolve name.

This shell function allows me to figure out what to put in:

  $ ipfs ls /inps/<local-ID>

And while we're at it, we also support ID queries on other peers via a
variadic argument.